[package]
name = "ghostwire-client"
version = "0.1.0"
edition = "2021"
authors = ["Ghostwire Team <team@ghostwire.dev>"]
description = "Ghostwire VPN client"
license = "MIT OR Apache-2.0"

[dependencies]
ghostwire-common = { path = "../ghostwire-common" }
tokio = { workspace = true }